name: Deno CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        deno: [canary]
        os: [macos-latest, ubuntu-latest, windows-2019]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Deno ${{ matrix.deno }}
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: ${{ matrix.deno }}
      - name: Run tests
        run: deno test --jobs 8 --allow-net --coverage=coverage/tmp --ignore=node_modules
      - name: Generate coverage
        run: deno coverage coverage/tmp --lcov > coverage/lcov.info; sed -i.bak -E 's/SF:.*\/([^/]+\.ts)/SF:\1/' coverage/lcov.info; rm -f coverage/lcov.info.bak
        if: matrix.os == 'ubuntu-latest' && matrix.deno == 'canary'
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        if: matrix.os == 'ubuntu-latest' && matrix.deno == 'canary'
        with:
          fail_ci_if_error: true
          files: lcov.info
          directory: coverage
